// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kpi.proto

package pbproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KpiType int32

const (
	KpiType_CPUInfo  KpiType = 0
	KpiType_TempInfo KpiType = 1
	KpiType_RamInfo  KpiType = 2
)

var KpiType_name = map[int32]string{
	0: "CPUInfo",
	1: "TempInfo",
	2: "RamInfo",
}

var KpiType_value = map[string]int32{
	"CPUInfo":  0,
	"TempInfo": 1,
	"RamInfo":  2,
}

func (x KpiType) String() string {
	return proto.EnumName(KpiType_name, int32(x))
}

func (KpiType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c38bdebe3e93bbf, []int{0}
}

type AdditionalMsg struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceName         string   `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Util                 float32  `protobuf:"fixed32,3,opt,name=util,proto3" json:"util,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdditionalMsg) Reset()         { *m = AdditionalMsg{} }
func (m *AdditionalMsg) String() string { return proto.CompactTextString(m) }
func (*AdditionalMsg) ProtoMessage()    {}
func (*AdditionalMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c38bdebe3e93bbf, []int{0}
}

func (m *AdditionalMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdditionalMsg.Unmarshal(m, b)
}
func (m *AdditionalMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdditionalMsg.Marshal(b, m, deterministic)
}
func (m *AdditionalMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdditionalMsg.Merge(m, src)
}
func (m *AdditionalMsg) XXX_Size() int {
	return xxx_messageInfo_AdditionalMsg.Size(m)
}
func (m *AdditionalMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AdditionalMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AdditionalMsg proto.InternalMessageInfo

func (m *AdditionalMsg) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *AdditionalMsg) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *AdditionalMsg) GetUtil() float32 {
	if m != nil {
		return m.Util
	}
	return 0
}

type Kpi struct {
	ResourceId           int32          `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ParentId             int32          `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	KpiType              KpiType        `protobuf:"varint,3,opt,name=kpi_type,json=kpiType,proto3,enum=pbproto.KpiType" json:"kpi_type,omitempty"`
	RaisedTs             float32        `protobuf:"fixed32,4,opt,name=raised_ts,json=raisedTs,proto3" json:"raised_ts,omitempty"`
	ReportedTs           float32        `protobuf:"fixed32,5,opt,name=reported_ts,json=reportedTs,proto3" json:"reported_ts,omitempty"`
	ResourceType         string         `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	AdditionalMessage    *AdditionalMsg `protobuf:"bytes,7,opt,name=additional_message,json=additionalMessage,proto3" json:"additional_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Kpi) Reset()         { *m = Kpi{} }
func (m *Kpi) String() string { return proto.CompactTextString(m) }
func (*Kpi) ProtoMessage()    {}
func (*Kpi) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c38bdebe3e93bbf, []int{1}
}

func (m *Kpi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kpi.Unmarshal(m, b)
}
func (m *Kpi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kpi.Marshal(b, m, deterministic)
}
func (m *Kpi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kpi.Merge(m, src)
}
func (m *Kpi) XXX_Size() int {
	return xxx_messageInfo_Kpi.Size(m)
}
func (m *Kpi) XXX_DiscardUnknown() {
	xxx_messageInfo_Kpi.DiscardUnknown(m)
}

var xxx_messageInfo_Kpi proto.InternalMessageInfo

func (m *Kpi) GetResourceId() int32 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *Kpi) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Kpi) GetKpiType() KpiType {
	if m != nil {
		return m.KpiType
	}
	return KpiType_CPUInfo
}

func (m *Kpi) GetRaisedTs() float32 {
	if m != nil {
		return m.RaisedTs
	}
	return 0
}

func (m *Kpi) GetReportedTs() float32 {
	if m != nil {
		return m.ReportedTs
	}
	return 0
}

func (m *Kpi) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Kpi) GetAdditionalMessage() *AdditionalMsg {
	if m != nil {
		return m.AdditionalMessage
	}
	return nil
}

func init() {
	proto.RegisterEnum("pbproto.KpiType", KpiType_name, KpiType_value)
	proto.RegisterType((*AdditionalMsg)(nil), "pbproto.AdditionalMsg")
	proto.RegisterType((*Kpi)(nil), "pbproto.Kpi")
}

func init() {
	proto.RegisterFile("kpi.proto", fileDescriptor_8c38bdebe3e93bbf)
}

var fileDescriptor_8c38bdebe3e93bbf = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x4d, 0xf7, 0xa7, 0xdd, 0xd9, 0x26, 0x33, 0x17, 0x52, 0xf0, 0xc2, 0x32, 0x6f, 0x8a,
	0xc2, 0xc0, 0xf9, 0x04, 0x22, 0x5e, 0x94, 0x31, 0x91, 0x50, 0xaf, 0x4b, 0x66, 0xe2, 0x08, 0x5d,
	0x93, 0x90, 0x64, 0x17, 0x7b, 0x15, 0x9f, 0x56, 0x9a, 0xac, 0x95, 0xdd, 0x9d, 0xfc, 0xbe, 0x9c,
	0xf3, 0x7d, 0xe7, 0xc0, 0xa4, 0xd6, 0x62, 0xa5, 0x8d, 0x72, 0x0a, 0xc7, 0x7a, 0xe7, 0x8b, 0xa5,
	0x80, 0xf9, 0x2b, 0x63, 0xc2, 0x09, 0x25, 0xe9, 0x61, 0x6b, 0xf7, 0xf8, 0x1e, 0xa6, 0x42, 0x5a,
	0x47, 0xe5, 0x37, 0xaf, 0x04, 0x4b, 0x51, 0x86, 0xf2, 0x11, 0x81, 0x0e, 0x15, 0x0c, 0x3f, 0xc0,
	0xbc, 0xff, 0x20, 0x69, 0xc3, 0xd3, 0x28, 0x43, 0xf9, 0x84, 0xcc, 0x3a, 0xf8, 0x41, 0x1b, 0x8e,
	0x31, 0x0c, 0x8f, 0x4e, 0x1c, 0xd2, 0x41, 0x86, 0xf2, 0x88, 0xf8, 0x7a, 0xf9, 0x1b, 0xc1, 0x60,
	0xa3, 0x45, 0xeb, 0x60, 0xb8, 0x55, 0x47, 0x73, 0xe1, 0xd0, 0xa1, 0x82, 0xe1, 0x3b, 0x98, 0x68,
	0x6a, 0xb8, 0x74, 0xad, 0x1c, 0x79, 0x39, 0x09, 0xa0, 0x60, 0xf8, 0x09, 0x92, 0x5a, 0x8b, 0xca,
	0x9d, 0x34, 0xf7, 0xd3, 0xaf, 0xd7, 0x8b, 0xd5, 0x79, 0x99, 0xd5, 0x46, 0x8b, 0xf2, 0xa4, 0x39,
	0x89, 0xeb, 0x50, 0xb4, 0x93, 0x0c, 0x15, 0x96, 0xb3, 0xca, 0xd9, 0x74, 0xe8, 0xb3, 0x24, 0x01,
	0x94, 0x36, 0xe4, 0xd0, 0xca, 0xb8, 0x20, 0x8f, 0xbc, 0x0c, 0x1d, 0x2a, 0x6d, 0xbb, 0x69, 0x1f,
	0xd4, 0xfb, 0x8d, 0xc3, 0xa6, 0x1d, 0xf4, 0x16, 0xef, 0x80, 0x69, 0x7f, 0xc0, 0xaa, 0xe1, 0xd6,
	0xd2, 0x3d, 0x4f, 0xe3, 0x0c, 0xe5, 0xd3, 0xf5, 0x6d, 0x9f, 0xec, 0xe2, 0xc6, 0xe4, 0xe6, 0xbf,
	0x63, 0x1b, 0x1a, 0x1e, 0x9f, 0x21, 0x3e, 0xa7, 0xc7, 0x53, 0x88, 0xdf, 0x3e, 0xbf, 0x0a, 0xf9,
	0xa3, 0x16, 0x57, 0x78, 0x06, 0x49, 0xc9, 0x1b, 0xed, 0x5f, 0xa8, 0x95, 0x08, 0x6d, 0xfc, 0x23,
	0xda, 0x8d, 0xfd, 0xe8, 0x97, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0x88, 0x12, 0x39, 0xd7,
	0x01, 0x00, 0x00,
}
